#!/usr/bin/env bash
# make-contact-sheet.sh — regenerate the SIMT-CFG contact sheet for the labeled corpus.
# For each ~/predicated_control_flows benchmark, run cfgraph on its kernel, render a PNG, and tile
# them all into out/index.html. Node shapes encode the EXEC-mask role from our classifier:
#   ▲ diverge (s_and_saveexec)   ▼ reconverge (s_or exec)   ▱ else arm   ⌂ && narrow
#
# Usage:  ./make-contact-sheet.sh
# Requires: a built ./build/cfgraph, graphviz `dot`, and the patched Dyninst libs on LD_LIBRARY_PATH.
set -euo pipefail

here="$(cd "$(dirname "$0")" && pwd)"
prefix="$here/../../build/dyninst"
export LD_LIBRARY_PATH="$prefix/lib64:${LD_LIBRARY_PATH:-}"

corpus="${CORPUS_DIR:-$HOME/predicated_control_flows}"
out="$here/out"
cfgraph="$here/build/cfgraph"

[ -x "$cfgraph" ] || { echo "error: $cfgraph not built (cmake --build build --target cfgraph)"; exit 1; }
command -v dot >/dev/null || { echo "error: graphviz 'dot' not found"; exit 1; }
mkdir -p "$out"

# pedagogical order: predication → ifs → elseif → switch/dispatch → loop → atomic → baseline
order="cndmsk if if_else_negated if_else_no_branch classic_if_else two_consecutive_if_else \
       if_elseif_else switch_case jump_table func_pointer whileloop atomic vectorAdd-7.0.2"

# --- per-benchmark: pick the kernel, dump DOT, render PNG ---
for name in $order; do
  obj=$(ls "$corpus/$name"/code-objects/*gfx908* 2>/dev/null | head -1) || true
  [ -n "${obj:-}" ] || { echo "skip $name (no gfx908 object)"; continue; }
  kernels=$(readelf -sW "$obj" 2>/dev/null | awk '{print $NF}' | grep '\.kd$' \
            | sed 's/\.kd$//' | c++filt 2>/dev/null | sed -E 's/\(.*//' | sort -u)
  kernel=$(echo "$kernels" | grep -x call_fn || echo "$kernels" | head -1)   # dispatch cases use call_fn
  "$cfgraph" "$obj" "$kernel" > "$out/$name.dot" 2>/dev/null
  dot -Tpng "$out/$name.dot" -o "$out/$name.png" 2>/dev/null
  echo "  $name -> $kernel"
done

# --- tile into index.html ---
cat > "$out/index.html" <<'HTML'
<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>SIMT CFG contact sheet — predicated_control_flows (gfx908)</title>
<style>
  :root { color-scheme: light dark; }
  body { font-family: system-ui, sans-serif; margin: 1.5rem; background:#fafafa; color:#111; }
  @media (prefers-color-scheme: dark){ body{background:#161616;color:#eee;} .card{background:#1e1e1e;border-color:#333;} .kern{color:#9cc;} }
  h1 { font-size:1.15rem; margin:0 0 .2rem; } code{font-family:monospace;}
  p.sub { margin:.1rem 0 1rem; color:#777; font-size:.85rem; }
  .legend { display:flex; gap:1rem; flex-wrap:wrap; font-size:.8rem; margin-bottom:1.2rem; }
  .grid { display:grid; grid-template-columns:repeat(auto-fill, minmax(320px,1fr)); gap:1rem; }
  .card { border:1px solid #ddd; border-radius:8px; background:#fff; padding:.5rem; display:flex; flex-direction:column; }
  figcaption { display:flex; flex-wrap:wrap; align-items:baseline; gap:.5rem; margin-bottom:.4rem; }
  .name { font-weight:700; font-family:monospace; } .kern { font-family:monospace; font-size:.8rem; color:#468; }
  .badges { margin-left:auto; font-size:.8rem; } .badges b { font-weight:600; margin-left:.3rem; }
  .d{color:#c8791a;} .r{color:#2b7fd6;} .e{color:#7a5af0;} .n{color:#b58a00;}
  .card img { width:100%; height:auto; max-height:420px; object-fit:contain; background:#fff; border-radius:4px; }
</style></head><body>
  <h1>SIMT control-flow contact sheet — <code>~/predicated_control_flows</code> (gfx908)</h1>
  <p class="sub">Generated by <code>cfgraph</code> (Dyninst + our EXEC-mask classifier). One kernel per benchmark. Click a tile for the full image.</p>
  <div class="legend">
    <span><b class="d">&#9650;</b> diverge (s_and_saveexec)</span>
    <span><b class="r">&#9660;</b> reconverge (s_or exec)</span>
    <span><b class="e">&#9645;</b> else arm</span>
    <span><b class="n">&#8962;</b> &amp;&amp; narrow</span>
  </div>
  <div class="grid">
HTML

for name in $order; do
  [ -f "$out/$name.png" ] || continue
  dot="$out/$name.dot"
  kernel=$(grep -oE 'label="[^"]+";' "$dot" | sed 's/label="//;s/";//' | grep -v '^legend$' | head -1)
  div=$(grep -c '\\ndiverge"' "$dot" || true);    rec=$(grep -c '\\nreconverge"' "$dot" || true)
  els=$(grep -c '\\nelse"' "$dot" || true);        amp=$(grep -c '\\n&&"' "$dot" || true)
  {
    echo "    <figure class=\"card\">"
    echo "      <figcaption><span class=\"name\">$name</span> <span class=\"kern\">$kernel</span>"
    echo "        <span class=\"badges\"><b class=\"d\">&#9650; $div</b> <b class=\"r\">&#9660; $rec</b> <b class=\"e\">&#9645; $els</b> <b class=\"n\">&#8962; $amp</b></span>"
    echo "      </figcaption>"
    echo "      <a href=\"$name.png\" target=\"_blank\"><img src=\"$name.png\" alt=\"$name CFG\" loading=\"lazy\"></a>"
    echo "    </figure>"
  } >> "$out/index.html"
done
echo "  </div></body></html>" >> "$out/index.html"

echo "wrote $out/index.html ($(grep -c 'class=\"card\"' "$out/index.html") tiles)"
